using AdventOfCode2023;

// Day1.Solve();
//Day2.Solve();
// Day3.Solve();
// Day4.Solve();
//Day5.Solve();
// Day6.Solve();
// Day7.Solve();
// Day8.Solve();
// Day9.Solve();
// Day10.Solve();
// Day12.Solve();
// Day13.Solve();
// Day14.Solve();
// Day15.Solve();
// Day16.Solve();
// Day17.Solve();
// Day18.Solve();
// Day19.Solve();
Day20.Solve();
